# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a16d890ae4691d2eb3e6d9b115d461fdd3782868f17ab50ecf69447070ef39a888e7036259942a13f1efa46bcf4134763a9cd3398f397fef20c075aae792c93
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID_INSTA"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET_INSTA"] %>

test:
  secret_key_base: ccf5227f73ed6259b2e1a5b23ee76e39247a4d1bfd76fa3c0036d37d8683926968bda398cc742bc50d29ce627e33ebd17e2def2f6bc96c563e5079a393d7de1f
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID_INSTA"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET_INSTA"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID_INSTA"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET_INSTA"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
